MY_PROEKT/MY_PROEKT/Controllers/DogovorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMatrix.WebData;
using MY_PROEKT.Models;
using System.Web.Security;

namespace MY_PROEKT.Controllers
{
    public class DogovorController : Controller
    {
        private UsersContext db = new UsersContext();
        [Authorize(Roles = "Admin, Agent, Client")]
        //
        // GET: /Dogovor/

       
        public ActionResult Index()
        {
           var user = db.Dogovors.Include(p => p.usluga1);
           var dogovor = user.Include(c => c.user1);
          
                  return View(dogovor.ToList());
         
        }

        //
        // GET: /Dogovor/Details/5

         [Authorize(Roles = "Admin, Client")]
        public ActionResult Details(int id = 0)
        {
            SelectList dogovor1 = new SelectList(db.Uslugas, "UslugaId", "Name");
            ViewBag.dog = dogovor1;
            SelectList Puser = new SelectList(db.UserProfiles, "UserId", "UserName");
            ViewBag.user2 = Puser;
            Dogovor dogovor = db.Dogovors.Find(id);
            if (dogovor == null)
            {
                return HttpNotFound();
            }
            return View(dogovor);
        }

        //
        // GET: /Dogovor/Create

         [Authorize(Roles = "Admin, Agent")]
        public ActionResult Create()
                     {
            
                SelectList dogovor = new SelectList(db.Uslugas, "UslugaId", "Name");
            ViewBag.dog = dogovor;
     //      SelectList Puser = new SelectList(db.UserProfiles, "UserId", "UserName");
                    List <agn> aa = new List<agn>();

                    foreach (var userk in db.UserProfiles)
                    {

                        if (Roles.GetRolesForUser(userk.UserName).Contains("Client"))
                        {
                            agn prom = new agn();
                            prom.UserId = userk.UserId;
                            prom.UserName = userk.UserName;
                            aa.Add(prom);
                        }
                    }

                    SelectList Puser = new SelectList(aa, "UserId", "UserName");
                    ViewBag.us = Puser;
                    Dogovor dogovor2 = new Dogovor();
               dogovor2.Data= DateTime.Now;
               dogovor2.AgentFio = User.Identity.Name;

          //   db.Dogovors.AgentFio=

               //   ViewBag.AgentFio = User.Identity.Name;


                    return View(dogovor2);
                    }

        //
        // POST: /Dogovor/Create
         [Authorize(Roles = "Admin, Agent")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Dogovor dogovor)
        {
            if (ModelState.IsValid)
            {
                dogovor.AgentFio = User.Identity.Name;
                dogovor.Data = DateTime.Now;
                db.Dogovors.Add(dogovor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(dogovor);
        
         }

        //
        // GET: /Dogovor/Edit/5

         [Authorize(Roles = "Admin, Agent")]
        public ActionResult Edit(int id = 0)
        {
            SelectList dogovor1 = new SelectList(db.Uslugas, "UslugaId", "Name");
            ViewBag.dog = dogovor1;
            SelectList Puser = new SelectList(db.UserProfiles, "UserId", "UserName");
            ViewBag.user2 = Puser;
            Dogovor dogovor2 = new Dogovor();
            dogovor2.AgentFio = User.Identity.Name;
            Dogovor dogovor = db.Dogovors.Find(id);
            if (dogovor == null)
            {
                return HttpNotFound();
            }
            return View(dogovor);
        }

        //
        // POST: /Dogovor/Edit/5
        [Authorize(Roles = "Admin, Agent")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Dogovor dogovor)
        {
            SelectList dogovor1 = new SelectList(db.Uslugas, "UslugaId", "Name");
            ViewBag.dog = dogovor1;
            SelectList Puser = new SelectList(db.UserProfiles, "UserId", "UserName");
            ViewBag.user2 = Puser;

            if (ModelState.IsValid)
            {
                db.Entry(dogovor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(dogovor);
        }

        //
        // GET: /Dogovor/Delete/5

         [Authorize(Roles = "Admin, Agent")]
        public ActionResult Delete(int id = 0)
        {
            Dogovor dogovor = db.Dogovors.Find(id);
            if (dogovor == null)
            {
                return HttpNotFound();
            }
            return View(dogovor);
        }

        //
        // POST: /Dogovor/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Dogovor dogovor = db.Dogovors.Find(id);
            db.Dogovors.Remove(dogovor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MY_PROEKT/MY_PROEKT/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.Web.Security;
using MY_PROEKT.Models;
using WebMatrix.WebData;
using MY_PROEKT.Filters;

namespace MY_PROEKT.Controllers
{
    [InitializeSimpleMembership]
    public class UserController : Controller
    {
        private UsersContext db = new UsersContext();
         [Authorize(Roles = "Admin, Agent")]
        public ActionResult Index()
        {
            return View(db.UserProfiles);
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(RegisterModel model, FormCollection form)
        {
            if (ModelState.IsValid)
            {
                WebSecurity.CreateUserAndAccount(model.UserName, model.Password);
                Roles.AddUserToRole(model.UserName, form["role"]);
                return RedirectToAction("Index");
            }
            return View(model);
        }
        [HttpGet]
        public ActionResult Delete(int id = 0)
        {
            var user = db.UserProfiles.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id = 0)
        {
            var user = db.UserProfiles.Find(id);
            if (user != null)
            {
                Roles.RemoveUserFromRoles(user.UserName, Roles.GetRolesForUser(user.UserName));
                Membership.DeleteUser(user.UserName, true);
            }
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult ChangeRole(int id = 0)
        {
            var user = db.UserProfiles.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }
        [HttpPost]
        public ActionResult ChangeRole(FormCollection form, int id = 0)
        {
            var user = db.UserProfiles.Find(id);
            if (user != null)
            {
                Roles.RemoveUserFromRole(user.UserName, Roles.GetRolesForUser(user.UserName)[0]);
                string role = form["role"];
                Roles.AddUserToRole(user.UserName, role);
            }
            return RedirectToAction("Index");
        }
        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MY_PROEKT/MY_PROEKT/Controllers/ZayvkaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMatrix.WebData;
using MY_PROEKT.Models;
using System.Web.Security;


namespace MY_PROEKT.Controllers
{
    public class ZayvkaController : Controller
    {
        private UsersContext db = new UsersContext();
        [Authorize(Roles = "Admin, Agent, Client")]
        //
        // GET: /Zayvka/
        public ActionResult Index()
        {
           var zayvk = db.Zayvkas.Include(t => t.usluga);
            var zayvkass = zayvk.Include(n => n.userp);
            return View(zayvkass.ToList());

                 }

        //
        // GET: /Zayvka/Details/5
        public ActionResult Details(int id = 0)
        {
            SelectList usl = new SelectList(db.Uslugas, "UslugaId", "Name");
            ViewBag.dog = usl;
            SelectList Puser = new SelectList(db.UserProfiles, "UserId", "UserName");
            ViewBag.user2 = Puser;
            Zayvka zayvka = db.Zayvkas.Find(id);
            if (zayvka == null)
            {
                return HttpNotFound();
            }
            return View(zayvka);
        }

        //
        // GET: /Zayvka/Create
        public ActionResult Create()
        {
            SelectList usl = new SelectList(db.Uslugas, "UslugaId", "Name");
            ViewBag.usln = usl;

            SelectList puser = new SelectList(db.UserProfiles.Where(item => item.UserId == WebSecurity.CurrentUserId), "UserId", "UserName");
            ViewBag.user2 = puser;
            DateTime dd = DateTime.Now;
            Zayvka zav = new Zayvka();
            zav.Datazayvka = dd;
            zav.Status = "На рассмотрении";
             return View(zav);
                   }

        //
        // POST: /Zayvka/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Zayvka zayvka)
        {
            if (ModelState.IsValid)
            {
                zayvka.Datazayvka = DateTime.Now;
                zayvka.Status = "На рассмотрении";
                db.Zayvkas.Add(zayvka);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(zayvka);
        }

        //
        // GET: /Zayvka/Edit/5

        public ActionResult Edit(int id = 0)
        {
            SelectList uslug = new SelectList(db.Uslugas, "UslugaId", "Name");
            ViewBag.usl = uslug;
            SelectList puser = new SelectList(db.UserProfiles.Where(item => item.UserId == WebSecurity.CurrentUserId), "UserId", "UserName");
            ViewBag.user2 = puser;
            Zayvka zayvka = db.Zayvkas.Find(id);
            zayvka.Datazayvka = DateTime.Now;
            zayvka.Status = "На рассмотрении";
            if (zayvka == null)
            {
              return HttpNotFound();
            }
            return View(zayvka);
        }

        //
        // POST: /Zayvka/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Zayvka zayvka)
        {
            zayvka.Datazayvka = DateTime.Now;
           // zayvka.Status = "На рассмотрении";  
            if (ModelState.IsValid)
            {
                              db.Entry(zayvka).State = EntityState.Modified;
                               db.SaveChanges();
                
                return RedirectToAction("Index");

            }
            return View(zayvka);
        }
        //
        // GET: /Zayvka/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Zayvka zayvka = db.Zayvkas.Find(id);
            if (zayvka == null)
            {
                return HttpNotFound();
            }
            return View(zayvka);
        }
        //
        // POST: /Zayvka/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Zayvka zayvka = db.Zayvkas.Find(id);
            db.Zayvkas.Remove(zayvka);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MY_PROEKT/MY_PROEKT/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
    <head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta charset="utf-8" />
        <title>@ViewBag.Title — приложение ASP.NET MVC</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                
                    <section id="login" class="float-right">
                        @Html.Partial("_LoginPartial")
                    </section>
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("СТРАХОВАЯ КОМПАНИЯ", "Index", "Home")</p>
                    <p class="site-title"></p>
                </div>
                <div class="float-right"><img src="~/images/imushestvo1.png" height="150" width="960" />
                    
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("УСЛУГИ", "Index", "Home")</li>
                            <li>@Html.ActionLink("ДОГОВОРА", "Index", "Dogovor")</li>
                            <li>@Html.ActionLink("ЗАЯВКИ", "Index", "Zayvka")</li>
                            <li>@Html.ActionLink("ПОЛЬЗОВАТЕЛИ", "Index", "User")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year —Механиков Денис, ИСТ-114</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>

MY_PROEKT/MY_PROEKT/Views/Shared/_Layout1.cshtml
<!DOCTYPE html>
<html lang="ru">
    <head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta charset="utf-8" />
        <title>@ViewBag.Title — приложение ASP.NET MVC</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("ваша эмблема здесь", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Домашняя страница", "Index", "Home")</li>
                            <li>@Html.ActionLink("О программе", "About", "Home")</li>
                            <li>@Html.ActionLink("Контакт", "Contact", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>Механиков — ИСТ-114</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>